[phases.build]
cmds = [
    "pip install -r requirements.txt",
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py migrate && python manage.py createsuperuser --noinput --username admin --email admin@hospital.com || true && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
