# Generated by Django 5.2.13 on 2026-04-30 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_orden', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(default='Emitida', max_length=50)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('fecha_estimada_entrega', models.DateTimeField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('presupuesto_asignado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('id_validacion_financiera', models.CharField(blank=True, max_length=100, null=True)),
                ('token_legal', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_producto', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(default='Activo', max_length=50)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('es_controlado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_proveedor', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(default='Activo', max_length=50)),
                ('nombre_proveedor', models.CharField(max_length=255)),
                ('nit_proveedor', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequisicionInterna',
            fields=[
                ('id_requisicion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_requisicion', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('area_solicitante', models.CharField(max_length=100)),
                ('origen', models.CharField(max_length=100)),
                ('mensaje_detalle', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('urgencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_detalle', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(default='Activo', max_length=50)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ordencompra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_ordenes', to='compras.producto')),
            ],
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='compras.proveedor'),
        ),
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id_proveedor_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_proveedor_producto', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(default='Activo', max_length=50)),
                ('precio_referencial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_actualizacion_precio', models.DateTimeField(auto_now=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='compras.producto')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_ofrecidos', to='compras.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionPedido',
            fields=[
                ('id_recepcion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_recepcion', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(default='Recibido', max_length=50)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('observaciones_recepcion', models.TextField(blank=True, null=True)),
                ('factura_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('factura_archivo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('recibido_conforme', models.BooleanField(default=True)),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='compras.ordencompra')),
            ],
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='id_requisicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_generadas', to='compras.requisicioninterna'),
        ),
    ]
