# Generated by Django 5.2.13 on 2026-05-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_detalleorden_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoMensual',
            fields=[
                ('id_presupuesto', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=7, unique=True)),
                ('monto_asignado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_disponible', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
