# Generated by Django 5.2.13 on 2026-05-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_presupuestomensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Emitida', 'Emitida'), ('En Tránsito', 'En Tránsito'), ('Recibida', 'Recibida'), ('Cancelada', 'Cancelada')], default='Emitida', max_length=50),
        ),
        migrations.AlterField(
            model_name='recepcionpedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Recibido', 'Recibido'), ('Rechazado', 'Rechazado')], default='Recibido', max_length=50),
        ),
    ]
